/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


public class HomePageForm extends javax.swing.JPanel {
    private MainUI main;
    /**
     * Creates new form AdminHomeForm
     */
    public HomePageForm(MainUI main) {
        this.main = main;
        initComponents();
        if(LoginForm.getUserType().equalsIgnoreCase("CUSTOMER")){
            enableHomePageAsCustomer();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFoodManagement = new javax.swing.JButton();
        btnEquipmentManagement = new javax.swing.JButton();
        btnVenueManagement = new javax.swing.JButton();
        btnSeeBookings = new javax.swing.JButton();
        lblwelcome = new javax.swing.JLabel();
        btnbkevent = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFoodManagement.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        btnFoodManagement.setText("Food Management");
        btnFoodManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodManagementActionPerformed(evt);
            }
        });
        add(btnFoodManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 390, 60));

        btnEquipmentManagement.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        btnEquipmentManagement.setText("Equipment Management");
        btnEquipmentManagement.setPreferredSize(new java.awt.Dimension(121, 23));
        btnEquipmentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipmentManagementActionPerformed(evt);
            }
        });
        add(btnEquipmentManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 390, 60));

        btnVenueManagement.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        btnVenueManagement.setText("Venue Management");
        btnVenueManagement.setPreferredSize(new java.awt.Dimension(121, 23));
        btnVenueManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenueManagementActionPerformed(evt);
            }
        });
        add(btnVenueManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 390, 60));

        btnSeeBookings.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        btnSeeBookings.setText("See Bookings");
        btnSeeBookings.setPreferredSize(new java.awt.Dimension(121, 23));
        btnSeeBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeBookingsActionPerformed(evt);
            }
        });
        add(btnSeeBookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 390, 60));

        lblwelcome.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 48)); // NOI18N
        lblwelcome.setText("Welcome");
        add(lblwelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 300, 50));

        btnbkevent.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        btnbkevent.setText("Book Event");
        btnbkevent.setPreferredSize(new java.awt.Dimension(121, 23));
        btnbkevent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbkeventActionPerformed(evt);
            }
        });
        add(btnbkevent, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 390, 60));

        btnlogout.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        btnlogout.setText("Log out");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 110, 39));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/406199-white-abstract-wallpaper.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEquipmentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipmentManagementActionPerformed
        // TODO add your handling code here:
        this.main.addComponent(new EquipmentManagementForm(this.main));
    }//GEN-LAST:event_btnEquipmentManagementActionPerformed

    private void btnFoodManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodManagementActionPerformed
        // TODO add your handling code here:
        this.main.addComponent(new FoodManagementForm(this.main));
    }//GEN-LAST:event_btnFoodManagementActionPerformed

    private void btnVenueManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenueManagementActionPerformed
        // TODO add your handling code here:
        this.main.addComponent(new VenueManagementForm(this.main));
    }//GEN-LAST:event_btnVenueManagementActionPerformed

    private void btnSeeBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeBookingsActionPerformed
        // TODO add your handling code here:
        this.main.addComponent(new BookingsForm(this.main));
    }//GEN-LAST:event_btnSeeBookingsActionPerformed

    private void btnbkeventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbkeventActionPerformed
        // TODO add your handling code here:
        this.main.addComponent(new EventForm(this.main));
    }//GEN-LAST:event_btnbkeventActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        this.main.addComponent(new LoginForm(this.main));
    }//GEN-LAST:event_btnlogoutActionPerformed

    public void enableHomePageAsCustomer() {
        btnFoodManagement.setText("See Food Menue");
        btnEquipmentManagement.setText("See Equipments");
        btnVenueManagement.setText("See Venues");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEquipmentManagement;
    private javax.swing.JButton btnFoodManagement;
    private javax.swing.JButton btnSeeBookings;
    private javax.swing.JButton btnVenueManagement;
    private javax.swing.JButton btnbkevent;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblwelcome;
    // End of variables declaration//GEN-END:variables
}
