/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LoginDao;
import Controller.RegistrationDao;
import Model.Login;
import Model.Manager;
import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author Ammar
 */
public class LoginForm extends javax.swing.JPanel {

    private MainUI main;
    private static String email;
    private static String usertype;
    private static String personID;
    /**
     * Creates new form LoginForm
     */
    public LoginForm(MainUI main) {
        this.main = main;
        initComponents();
        txtemail.setText("maaz@yahoo.com");
        txtpassword.setText("aaa");
        //reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        btnregister = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel1.setText("Email");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 90, 31));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 90, 30));
        add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 221, 40));
        add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 221, 40));

        btnregister.setText("Register");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 80, 40));

        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 80, 40));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel3.setText("       Login Form");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 360, 34));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/406199-white-abstract-wallpaper.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        // TODO add your handling code here:
        this.main.addComponent(new RegistrationForm(this.main));
    }//GEN-LAST:event_btnregisterActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        email = txtemail.getText();
        if(validateFields()){
            Person person = RegistrationDao.getPersonByEmail(email);
            usertype = person.getUserType();
            personID = person.getId();
            this.main.addComponent(new HomePageForm(this.main));
        }        
    }//GEN-LAST:event_btnloginActionPerformed
    
    private void reset(){
        txtemail.setText(null);
        txtpassword.setText(null);
    }
    
    private boolean validateFields(){
        if(txtemail.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(LoginForm.this, "Enter email");
            txtemail.grabFocus();
            return false;
        }
        else if(!RegistrationDao.isEmailExisted(txtemail.getText())){
            JOptionPane.showMessageDialog(LoginForm.this, "Email does not exists. Please Register Yourself");
            txtemail.grabFocus();
            return false;
        }
        else if(txtpassword.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(LoginForm.this, "Enter password");
            txtpassword.grabFocus();
            return false;
        }
        else if(!LoginDao.isPasswordMatched(new Login(txtemail.getText(),txtpassword.getText()))){
            JOptionPane.showMessageDialog(LoginForm.this, "Incorrect password");
            txtpassword.grabFocus();
            return false;
        }
        return true;
}
    public static String getEmail(){
        return email;
    }
    
    public static String getUserType(){
        return usertype;
    }
    
    public static String getPersonID(){
        return personID;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnregister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
