/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.RegistrationDao;
import Model.Customer;
import Model.Login;
import Model.Manager;
import Model.Person;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Ammar
 */
public class RegistrationForm extends javax.swing.JPanel {
    private MainUI main;
    /**
     * Creates new form RegistrationFarm
     */
    public RegistrationForm(MainUI main) {
        this.main = main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnregister = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        txtphn = new javax.swing.JTextField();
        cmbgender = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        cmbusertype = new javax.swing.JComboBox<>();
        txtemail = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txtretypepassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnclear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel2.setText("Phone Number");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel3.setText("Gender");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 40));

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel5.setText("Type");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel7.setText("Password");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        btnregister.setText("Register");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 590, 80, 40));

        btncancel.setText("Back");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 590, 80, 40));
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 200, 40));
        add(txtphn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 200, 40));

        cmbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select One--", "Female", "Male" }));
        add(cmbgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 200, 40));

        txtaddress.setColumns(20);
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 200, -1));

        cmbusertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select One--", "Customer", "Manager", " " }));
        add(cmbusertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 200, 40));
        add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 200, 40));
        add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 200, 40));

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel8.setText("ReType Password");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));
        add(txtretypepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 200, 40));

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        jLabel9.setText("    Registration Form");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 300, 40));

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel4.setText("Address");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, 30));

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, 80, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/406199-white-abstract-wallpaper.jpg"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        // TODO add your handling code here:
        if(validateFields()){
            String id = UUID.randomUUID().toString();
            String name = txtname.getText();
            String gender = (String)cmbgender.getSelectedItem();
            String no = txtphn.getText();
            String address = txtaddress.getText();
            String type = (String)cmbusertype.getSelectedItem();
            String loginid = UUID.randomUUID().toString();
            String email = txtemail.getText();
            String password = txtpassword.getText();
            Login login = new Login(loginid,email,password);
            Person person;
            if(type.equals("Manager")){
                person = new Manager(id,name,gender,no,address,type);
            }
            else{
                person = new Customer(id,name,gender,no,address,type);
            }
            boolean flag = RegistrationDao.addPerson(person, login);
            if (flag){
                JOptionPane.showMessageDialog(RegistrationForm.this, "Registration Successfull");
            }
            else{
                JOptionPane.showMessageDialog(RegistrationForm.this, "Something went wrong");
            }
        }
        
        
    }//GEN-LAST:event_btnregisterActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        this.main.addComponent(new LoginForm(this.main));
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnclearActionPerformed

    private void reset(){
        txtemail.setText(null);
        txtpassword.setText(null);
        txtaddress.setText(null);
        txtretypepassword.setText(null);
        txtphn.setText(null);
        txtname.setText(null);
        cmbgender.setSelectedIndex(0);
        cmbusertype.setSelectedIndex(0);
    }
    
    private boolean validateFields(){
        if(txtname.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Enter name");
            txtname.grabFocus();
            return false;
        }
        else if(txtphn.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Enter Phone Number");
            txtphn.grabFocus();
            return false;
        }
        else if(RegistrationDao.isPhoneNumberExisted(txtphn.getText())){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Phone Number already exists");
            txtphn.grabFocus();
            return false;
        }
        else if(cmbgender.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Select Gender");;
            return false;
        }
        else if(txtaddress.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Enter address");
            txtaddress.grabFocus();
            return false;
        }
        else if(cmbusertype.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Select User Type");
            return false;
        }
        else if(txtemail.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Enter email");
            txtemail.grabFocus();
            return false;
        }
        else if(!isEmailPatternValid()){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Invalid Email Pattern");
            txtemail.grabFocus();
            return false;
        }
        else if(RegistrationDao.isEmailExisted(txtemail.getText())){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Email already exists");
            txtemail.grabFocus();
            return false;
        }
        else if(txtpassword.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Enter password");
            txtpassword.grabFocus();
            return false;
        }
        else if(txtretypepassword.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Enter Retype Password");
            txtretypepassword.grabFocus();
            return false;
        }
        else if(!(txtpassword.getText()).equals(txtretypepassword.getText())){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Password is not matched");
            //txtretypepassword.grabFocus();
            return false;
        }
        return true;
    }
    
    private boolean isEmailPatternValid(){
        String regex = "^(.+)@(.+)$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(txtemail.getText());
        return matcher.matches();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnregister;
    private javax.swing.JComboBox<String> cmbgender;
    private javax.swing.JComboBox<String> cmbusertype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtphn;
    private javax.swing.JPasswordField txtretypepassword;
    // End of variables declaration//GEN-END:variables
}
